//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystemV4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.PROJECTs = new HashSet<PROJECT>();
            this.TIMESHEETs = new HashSet<TIMESHEET>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int Employee_ID { get; set; }
        [Display(Name = "Employee First Name")]
        public string F_name { get; set; }
        [Display(Name = "Employee Type")]
        public string Employee_type { get; set; }
        [Display(Name = "Hourly Rate")]
        public double Hourly_rate { get; set; }
        [Display(Name = "Middle Name")]
        public string M_name { get; set; }
        [Display(Name = "Last Name")]
        public string L_name { get; set; }
        [Display(Name = "Last Update")]
        public Nullable<System.DateTime> Last_update { get; set; }
        [Display(Name = "Last Update By")]
        public string Last_update_by { get; set; }
        [Display(Name = "Email Address")]
        public string Email_address { get; set; }
    
        public virtual EMPLOYEE_DELIVERABLE EMPLOYEE_DELIVERABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT> PROJECTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMESHEET> TIMESHEETs { get; set; }
        public virtual User_login User_login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
