//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystemV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_AllProjects
    {
        public string Name { get; set; }
        public int Project_ID { get; set; }
        public string USA_region { get; set; }
        public System.DateTime Deadline { get; set; }
        public System.DateTime Start_date { get; set; }
        public string Progress_status { get; set; }
        public int Manager_ID { get; set; }
    }
}
